export const GET_COUPON_REQUEST = "GET_COUPON_REQUEST";
export const GET_COUPON_SUCCESS = "GET_COUPON_SUCCESS";
export const GET_COUPON_FAILURE = "GET_COUPON_FAILURE";

export const POST_COUPON_REQUEST = "POST_COUPON_REQUEST";
export const POST_COUPON_SUCCESS = "POST_COUPON_SUCCESS";
export const POST_COUPON_FAILURE = "POST_COUPON_FAILURE";

export const DELETE_COUPON_REQUEST = "DELETE_COUPON_REQUEST";
export const DELETE_COUPON_SUCCESS = "DELETE_COUPON_SUCCESS";
export const DELETE_COUPON_FAILURE = "DELETE_COUPON_FAILURE";


export const EDIT_COUPON_REQUEST = "EDIT_COUPON_REQUEST";
export const EDIT_COUPON_SUCCESS = "EDIT_COUPON_SUCCESS";
export const EDIT_COUPON_FAILURE = "EDIT_COUPON_FAILURE";